/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_v1_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sectors/{sector_id}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sector Latest */
        get: operations["get_sector_latest_api_v1_sectors__sector_id__latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols/{code}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Symbol Latest */
        get: operations["get_symbol_latest_api_v1_symbols__code__latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_v1_artifacts__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_api_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_api_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy */
        get: operations["get_strategy_api_v1_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/sectors/{sector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sector Center */
        get: operations["get_sector_center_api_v1_analysis_sectors__sector_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/sectors/{sector_id}/leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sector Leaders */
        get: operations["get_sector_leaders_api_v1_analysis_sectors__sector_id__leaders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/symbols/{symbol}/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Symbol Value */
        get: operations["get_symbol_value_api_v1_analysis_symbols__symbol__value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/market/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Overview */
        get: operations["get_market_overview_api_v1_analysis_market_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/symbols/{symbol}/supply-chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supply Chain */
        get: operations["get_supply_chain_api_v1_analysis_symbols__symbol__supply_chain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AlertListResponse */
        AlertListResponse: {
            /** Items */
            items: components["schemas"]["AlertResponse"][];
        };
        /**
         * AlertPriority
         * @enum {string}
         */
        AlertPriority: "high" | "medium" | "low";
        /** AlertResponse */
        AlertResponse: {
            /**
             * Alert Id
             * Format: uuid
             */
            alert_id: string;
            /** Rule Id */
            rule_id: string;
            subject: components["schemas"]["SubjectRef"];
            priority: components["schemas"]["AlertPriority"];
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Evidence */
            evidence: string[];
            /** Artifact Run Id */
            artifact_run_id?: string | null;
            /** Open Chat Thread Id */
            open_chat_thread_id?: string | null;
            /** Parent Alert Id */
            parent_alert_id?: string | null;
            /** Channels */
            channels?: {
                [key: string]: unknown;
            };
            /**
             * State
             * @enum {string}
             */
            state: "active" | "capped" | "deferred" | "suppressed" | "sent" | "merged";
            /** Reason */
            reason?: string | null;
            /** Ctx */
            ctx?: {
                [key: string]: unknown;
            };
            /** Follow Up */
            follow_up?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at?: string | null;
        };
        /** AnalysisArtifactResponse */
        AnalysisArtifactResponse: {
            /** Run Id */
            run_id?: string;
            /** Skill */
            skill: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            subject: components["schemas"]["SubjectRef"];
            /** Summary */
            summary: string;
            /** Highlights */
            highlights: components["schemas"]["Highlight"][];
            /** Conclusions */
            conclusions: components["schemas"]["Conclusion"][];
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Charts */
            charts?: components["schemas"]["ChartSpec"][];
            /** References */
            references?: string[];
            /** Raw Pointer */
            raw_pointer: string;
        };
        /** Artifact */
        Artifact: {
            /** Run Id */
            run_id?: string;
            /** Skill */
            skill: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            subject: components["schemas"]["SubjectRef"];
            /** Summary */
            summary: string;
            /** Highlights */
            highlights?: components["schemas"]["Highlight"][];
            /** Conclusions */
            conclusions?: components["schemas"]["Conclusion"][];
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Charts */
            charts?: components["schemas"]["ChartSpec"][];
            /** References */
            references?: string[];
            /** Raw Pointer */
            raw_pointer: string;
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Run Id */
            run_id?: string;
            /** Skill */
            skill: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            subject: components["schemas"]["SubjectRef"];
            /** Summary */
            summary: string;
            /** Highlights */
            highlights?: components["schemas"]["Highlight"][];
            /** Conclusions */
            conclusions?: components["schemas"]["Conclusion"][];
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Charts */
            charts?: components["schemas"]["ChartSpec"][];
            /** References */
            references?: string[];
            /** Raw Pointer */
            raw_pointer: string;
        };
        /** ChartSpec */
        ChartSpec: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Series */
            series?: {
                [key: string]: unknown;
            }[];
        };
        /** Conclusion */
        Conclusion: {
            /** Claim */
            claim: string;
            /**
             * Relation Class
             * @enum {string}
             */
            relation_class: "fact" | "statistical" | "inferred";
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Highlight */
        Highlight: {
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warn" | "critical";
            /** Text */
            text: string;
        };
        /** PingResponse */
        PingResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /** RunResponse */
        RunResponse: {
            /** Id */
            id: string;
            /** Skill */
            skill: string;
            /** State */
            state: string;
            /** Artifact Run Id */
            artifact_run_id: string;
            /** Usage */
            usage?: {
                [key: string]: unknown;
            };
            /** Trace */
            trace?: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SectorLatestResponse */
        SectorLatestResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Metric Coverage */
            metric_coverage: number;
            /** Leaders */
            leaders: {
                [key: string]: unknown;
            }[];
            /** Members */
            members: {
                [key: string]: unknown;
            }[];
            /** Fund Flow */
            fund_flow: {
                [key: string]: unknown;
            };
            /** Valuation */
            valuation: {
                [key: string]: unknown;
            };
            artifact: components["schemas"]["Artifact"];
        };
        /** StrategyListResponse */
        StrategyListResponse: {
            /** Items */
            items: components["schemas"]["StrategyResponse"][];
        };
        /** StrategyResponse */
        StrategyResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
            /** Dsl */
            dsl: {
                [key: string]: unknown;
            };
            /** Last Candidate */
            last_candidate?: {
                [key: string]: unknown;
            } | null;
        };
        /** SubjectRef */
        SubjectRef: {
            /** Type */
            type: string;
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
        };
        /** SymbolLatestResponse */
        SymbolLatestResponse: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Sector Id */
            sector_id: string;
            /** Summary */
            summary: string;
            /** Leader Score */
            leader_score: {
                [key: string]: unknown;
            };
            /** Value */
            value: {
                [key: string]: unknown;
            };
            /** Supply Chain */
            supply_chain: {
                [key: string]: unknown;
            };
            /** Artifacts */
            artifacts: components["schemas"]["Artifact"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type SchemaAlertListResponse = components['schemas']['AlertListResponse'];
export type SchemaAlertPriority = components['schemas']['AlertPriority'];
export type SchemaAlertResponse = components['schemas']['AlertResponse'];
export type SchemaAnalysisArtifactResponse = components['schemas']['AnalysisArtifactResponse'];
export type SchemaArtifact = components['schemas']['Artifact'];
export type SchemaArtifactResponse = components['schemas']['ArtifactResponse'];
export type SchemaChartSpec = components['schemas']['ChartSpec'];
export type SchemaConclusion = components['schemas']['Conclusion'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaHighlight = components['schemas']['Highlight'];
export type SchemaPingResponse = components['schemas']['PingResponse'];
export type SchemaRunResponse = components['schemas']['RunResponse'];
export type SchemaSectorLatestResponse = components['schemas']['SectorLatestResponse'];
export type SchemaStrategyListResponse = components['schemas']['StrategyListResponse'];
export type SchemaStrategyResponse = components['schemas']['StrategyResponse'];
export type SchemaSubjectRef = components['schemas']['SubjectRef'];
export type SchemaSymbolLatestResponse = components['schemas']['SymbolLatestResponse'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ping_api_v1_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
        };
    };
    get_sector_latest_api_v1_sectors__sector_id__latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorLatestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_symbol_latest_api_v1_symbols__code__latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolLatestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
        };
    };
    get_alert_api_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_v1_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyListResponse"];
                };
            };
        };
    };
    get_strategy_api_v1_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_center_api_v1_analysis_sectors__sector_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_leaders_api_v1_analysis_sectors__sector_id__leaders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_symbol_value_api_v1_analysis_symbols__symbol__value_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_overview_api_v1_analysis_market_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisArtifactResponse"];
                };
            };
        };
    };
    get_supply_chain_api_v1_analysis_symbols__symbol__supply_chain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
